# Site settings
title: "Karthick Durai"
description: "Get to Know Karthick"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Karthick Durai"
resume_title:                   "Data Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dkarthicks27@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "None"
resume_contact_address:         "None"

resume_header_contact_info:     "None"
display_header_contact_info:    "false"

resume_header_intro: "<p>A seasoned <b>data scientist</b> with a background in full-stack software development. I’ve built end-to-end systems, explored the entire tech stack, and eventually found my passion in data and AI. Since then, I’ve worked on impactful projects like Graph RAGs, Agents to address multi-hop Q&A problems, and have fine-tuned LLMs using PEFT. I enjoy turning complex data into smart, real-world solutions—and I’m always experimenting, teaching, and learning along the way.</p>"
# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/dkarthicks27"
  resume_linkedin_url:          "https://www.linkedin.com/in/karthick-durai-618701123/"
  resume_website_url:           "https://karthickdurai.cloud/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
